Update dashboard.yml

diff --git a/.github/workflows/dashboard.yml b/.github/workflows/dashboard.yml
--- a/.github/workflows/dashboard.yml
+++ b/.github/workflows/dashboard.yml
@@ -32,10 +32,10 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r runs_requirements.txt
-      - name: Run Python Script
-        run: |
-          cd dashboard/HuggingFace/Dashboard_Archive
-          python new.py
+      # - name: Run Python Script
+      #   run: |
+      #     cd dashboard/HuggingFace/Dashboard_Archive
+      #     python new.py
       - name: Run Python Script from other folder to create README in main folder
         run: |
           cd dashboard/HuggingFace
@@ -58,26 +58,26 @@ jobs:
             echo "No changes to commit or there was an error. Skipping commit and push."
           fi
           
-      - name: Add Generated File
-        run: |
-          git config user.email "${{ secrets.USER_EMAIL }}"
-          git config user.name "${{ secrets.USER_NAME }}"
-          git pull origin main
-          cd dashboard/HuggingFace/Dashboard_Archive
-          # Get the current date and time (again)
-          current_date=$(date +"%Y%m%d")
-          # Create a README file with the current datetime in the filename
-          readme_filename="README_${current_date}.md"
-          # Add the generated README file
-          git add "$readme_filename"
-          set +e
-          # Commit and push the changes
-          git commit -m "Add $readme_filename"
-          commit_status=$?
-          set -e
-          if [ $commit_status -eq 0 ]; then
-              git push
-          else
-            echo "No changes to commit or there was an error. Skipping commit and push."
-          fi
+      # - name: Add Generated File
+      #   run: |
+      #     git config user.email "${{ secrets.USER_EMAIL }}"
+      #     git config user.name "${{ secrets.USER_NAME }}"
+      #     git pull origin main
+      #     cd dashboard/HuggingFace/Dashboard_Archive
+      #     # Get the current date and time (again)
+      #     current_date=$(date +"%Y%m%d")
+      #     # Create a README file with the current datetime in the filename
+      #     readme_filename="README_${current_date}.md"
+      #     # Add the generated README file
+      #     git add "$readme_filename"
+      #     set +e
+      #     # Commit and push the changes
+      #     git commit -m "Add $readme_filename"
+      #     commit_status=$?
+      #     set -e
+      #     if [ $commit_status -eq 0 ]; then
+      #         git push
+      #     else
+      #       echo "No changes to commit or there was an error. Skipping commit and push."
+      #     fi
         
