Update dashboard.yml

diff --git a/.github/workflows/dashboard.yml b/.github/workflows/dashboard.yml
--- a/.github/workflows/dashboard.yml
+++ b/.github/workflows/dashboard.yml
@@ -42,31 +42,14 @@ jobs:
         run: |
           cd dashboard/HuggingFace
           python dummy2.py
-      # - name: Add Generated File
-      #   run: |
-      #     git config user.email "${{ secrets.USER_EMAIL }}"
-      #     git config user.name "${{ secrets.USER_NAME }}"
-      #     git pull origin main
-      #     cd dashboard/HuggingFace
-      #     git add README.md     
-          
-      #     # Attempt to commit changes and handle errors
-      #     set +e
-      #     git commit -m "Add README.md"
-      #     commit_status=$?
-      #     set -e
-      #     if [ $commit_status -eq 0 ]; then
-      #       git push
-      #     else
-      #       echo "No changes to commit or there was an error. Skipping commit and push."
-      #     fi
-      - name: Add failed model list text file
+      - name: Add Generated File
         run: |
           git config user.email "${{ secrets.USER_EMAIL }}"
           git config user.name "${{ secrets.USER_NAME }}"
-          git pull origin main  
-          cd tests/config
-          git add failed_models.txt
+          git pull origin main
+          cd dashboard/HuggingFace
+          git add failed_models.txt    
+          
           # Attempt to commit changes and handle errors
           set +e
           git commit -m "Add failed_models.txt"
@@ -77,6 +60,23 @@ jobs:
           else
             echo "No changes to commit or there was an error. Skipping commit and push."
           fi
+      # - name: Add failed model list text file
+      #   run: |
+      #     git config user.email "${{ secrets.USER_EMAIL }}"
+      #     git config user.name "${{ secrets.USER_NAME }}"
+      #     git pull origin main  
+      #     cd tests/config
+      #     git add failed_models.txt
+      #     # Attempt to commit changes and handle errors
+      #     set +e
+      #     git commit -m "Add failed_models.txt"
+      #     commit_status=$?
+      #     set -e
+      #     if [ $commit_status -eq 0 ]; then
+      #       git push
+      #     else
+      #       echo "No changes to commit or there was an error. Skipping commit and push."
+      #     fi
       # - name: Add Generated File
       #   run: |
       #     git config user.email "${{ secrets.USER_EMAIL }}"
