Update dashboard.yml

diff --git a/.github/workflows/dashboard.yml b/.github/workflows/dashboard.yml
--- a/.github/workflows/dashboard.yml
+++ b/.github/workflows/dashboard.yml
@@ -42,24 +42,24 @@ jobs:
         run: |
           cd dashboard/HuggingFace
           python dummy2.py
-      - name: Add Generated File
-        run: |
-          git config user.email "${{ secrets.USER_EMAIL }}"
-          git config user.name "${{ secrets.USER_NAME }}"
-          git pull origin main
-          cd dashboard/HuggingFace
-          git add README.md     
+      # - name: Add Generated File
+      #   run: |
+      #     git config user.email "${{ secrets.USER_EMAIL }}"
+      #     git config user.name "${{ secrets.USER_NAME }}"
+      #     git pull origin main
+      #     cd dashboard/HuggingFace
+      #     git add README.md     
           
-          # Attempt to commit changes and handle errors
-          set +e
-          git commit -m "Add README.md"
-          commit_status=$?
-          set -e
-          if [ $commit_status -eq 0 ]; then
-            git push
-          else
-            echo "No changes to commit or there was an error. Skipping commit and push."
-          fi
+      #     # Attempt to commit changes and handle errors
+      #     set +e
+      #     git commit -m "Add README.md"
+      #     commit_status=$?
+      #     set -e
+      #     if [ $commit_status -eq 0 ]; then
+      #       git push
+      #     else
+      #       echo "No changes to commit or there was an error. Skipping commit and push."
+      #     fi
       - name: Add failed model list text file
         run: |
           git config user.email "${{ secrets.USER_EMAIL }}"
