Update deploy_multiple_models.yml

diff --git a/.github/workflows/deploy_multiple_models.yml b/.github/workflows/deploy_multiple_models.yml
--- a/.github/workflows/deploy_multiple_models.yml
+++ b/.github/workflows/deploy_multiple_models.yml
@@ -39,5 +39,5 @@ jobs:
       run: python deploy_multiple_models.py 
       working-directory: tests/src
     - name: trigger-next-model-step
-      if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
-      run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
+      # if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
+      # run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
