Update Latest_Model.yml

diff --git a/.github/workflows/Latest_Model.yml b/.github/workflows/Latest_Model.yml
--- a/.github/workflows/Latest_Model.yml
+++ b/.github/workflows/Latest_Model.yml
@@ -33,3 +33,22 @@ jobs:
 
       - name: Run Python Script
         run: python automate_list.py
+
+      - name: Add Generated File
+        run: |
+          git config user.email "${{ secrets.USER_EMAIL }}"
+          git config user.name "${{ secrets.USER_NAME }}"
+          git pull origin main
+          cd tests/config
+          git add lastweek_updated_models_min10.csv         
+          # Attempt to commit changes and handle errors
+          set +e
+          git commit -m "lastweek_updated_models_min10.csv"
+          commit_status=$?
+          set -e
+          if [ $commit_status -eq 0 ]; then
+            git push
+          else
+            echo "No changes to commit or there was an error. Skipping commit and push."
+          fi
+        
