Update new.yml

diff --git a/.github/workflows/new.yml b/.github/workflows/new.yml
--- a/.github/workflows/new.yml
+++ b/.github/workflows/new.yml
@@ -47,36 +47,36 @@ jobs:
         run: |
           cd dashboard/HuggingFace
           python new.py
-      # - name: Generate README file
-      #   run: |
-      #     cd dashboard/HuggingFace
+      - name: Generate README file
+        run: |
+          cd dashboard/HuggingFace/RunStatusDashboard_Archive
 
  
 
-      #     # Get the current date and time
-      #     current_date=$(date +"%Y%m%d")
+          # Get the current date and time
+          current_date=$(date +"%Y%m%d")
 
  
 
-      #     # Create a README file with the current datetime in the filename
-      #     readme_filename="README_${current_date}.md"
-      # - name: Add Generated README File
-      #   run: |
-      #     git config user.email "${{ secrets.USER_EMAIL }}"
-      #     git config user.name "${{ secrets.USER_NAME }}"
-      #     git pull origin main
-      #     cd dashboard/HuggingFace
-      #     git add README.md          
-      #     # Attempt to commit changes and handle errors
-      #     set +e
-      #     git commit -m "Add README.md"
-      #     commit_status=$?
-      #     set -e
-      #     if [ $commit_status -eq 0 ]; then
-      #       git push
-      #     else
-      #       echo "No changes to commit or there was an error. Skipping commit and push."
-      #     fi
+          # Create a README file with the current datetime in the filename
+          readme_filename="README_${current_date}.md"
+      - name: Add Generated README File
+        run: |
+          git config user.email "${{ secrets.USER_EMAIL }}"
+          git config user.name "${{ secrets.USER_NAME }}"
+          git pull origin main
+          cd dashboard/HuggingFace
+          git add README.md          
+          # Attempt to commit changes and handle errors
+          set +e
+          git commit -m "Add README.md"
+          commit_status=$?
+          set -e
+          if [ $commit_status -eq 0 ]; then
+            git push
+          else
+            echo "No changes to commit or there was an error. Skipping commit and push."
+          fi
 
       - name: Add Generated README File with TimeStamp
         run: |
