Update new.yml

diff --git a/.github/workflows/new.yml b/.github/workflows/new.yml
--- a/.github/workflows/new.yml
+++ b/.github/workflows/new.yml
@@ -78,30 +78,30 @@ jobs:
             echo "No changes to commit or there was an error. Skipping commit and push."
           fi
 
-      - name: Add Generated README File with TimeStamp
-        run: |
-          git config user.email "${{ secrets.USER_EMAIL }}"
-          git config user.name "${{ secrets.USER_NAME }}"
-          git pull origin main
-          cd dashboard/HuggingFace/RunStatusDashboard_Archive
-          # Get the current date and time (again)
-          current_date=$(date +"%Y%m%d")
+      # - name: Add Generated README File with TimeStamp
+      #   run: |
+      #     git config user.email "${{ secrets.USER_EMAIL }}"
+      #     git config user.name "${{ secrets.USER_NAME }}"
+      #     git pull origin main
+      #     cd dashboard/HuggingFace/RunStatusDashboard_Archive
+      #     # Get the current date and time (again)
+      #     current_date=$(date +"%Y%m%d")
           
-          # Create a README file with the current datetime in the filename
-          readme_filename="README_${current_date}.md"
+      #     # Create a README file with the current datetime in the filename
+      #     readme_filename="README_${current_date}.md"
 
  
 
-          # Add the generated README file
-          git add "$readme_filename"
-          set +e
-          # Commit and push the changes
-          git commit -m "Add $readme_filename"
-          commit_status=$?
-          set -e
-          if [ $commit_status -eq 0 ]; then
-              git push
-          else
-            echo "No changes to commit or there was an error. Skipping commit and push."
-          fi
+      #     # Add the generated README file
+      #     git add "$readme_filename"
+      #     set +e
+      #     # Commit and push the changes
+      #     git commit -m "Add $readme_filename"
+      #     commit_status=$?
+      #     set -e
+      #     if [ $commit_status -eq 0 ]; then
+      #         git push
+      #     else
+      #       echo "No changes to commit or there was an error. Skipping commit and push."
+      #     fi
          
