Update new.yml

diff --git a/.github/workflows/new.yml b/.github/workflows/new.yml
--- a/.github/workflows/new.yml
+++ b/.github/workflows/new.yml
@@ -4,22 +4,23 @@ on:
   workflow_dispatch
 
 jobs:
-  update-readme:
+  testing:
     runs-on: ubuntu-latest
+    
     env:
       token: ${{ secrets.API_TOKEN }}
       GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
-        # with:
+        uses: actions/checkout@v3
+        with:
         # # ref: main
-        #   lfs: true
-        #   repository: Konjarla-Vindya/son-azureml-oss-models
-        #   branch: main
+            lfs: true
+            repository: Konjarla-Vindya/son-azureml-oss-models
+            branch: main
         # #     git config global init.defaultBranch main
-        #   token: ${{ secrets.WORKFLOW_TOKEN }}
+            token: ${{ secrets.WORKFLOW_TOKEN }}
 
 
       - name: Set up Python
@@ -31,7 +32,10 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r runs_requirements.txt
-
+      - name: Run Python Script
+        run: |
+          cd dashboard/HuggingFace
+          python new.py
       - name: Generate README file
         run: |
           cd dashboard/HuggingFace
@@ -59,8 +63,14 @@ jobs:
 
           # Add the generated README file
           git add "$readme_filename"
-
+          set +e
           # Commit and push the changes
           git commit -m "Add $readme_filename"
-          git push
+          commit_status=$?
+          set -e
+          if [ $commit_status -eq 0 ]; then
+              git push
+          else
+            echo "No changes to commit or there was an error. Skipping commit and push."
+          fi
       
