Update new.yml

diff --git a/.github/workflows/new.yml b/.github/workflows/new.yml
--- a/.github/workflows/new.yml
+++ b/.github/workflows/new.yml
@@ -1,29 +1,15 @@
 name: Update README with Timestamp
 
- 
-
- 
-
 on:
   workflow_dispatch
-
- 
-
- 
 
 jobs:
   testing:
     runs-on: ubuntu-latest
 
- 
-
     env:
       token: ${{ secrets.WORKFLOW_TOKEN }}
       # GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
-
- 
-
- 
 
     steps:
       - name: Checkout code
@@ -36,20 +22,11 @@ jobs:
         # #     git config global init.defaultBranch main
             token: ${{ secrets.WORKFLOW_TOKEN }}
 
- 
-
- 
-
- 
 
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: 3.10.10
-
- 
-
- 
+          python-version: 3.10.
 
       - name: Install dependencies
         run: |
@@ -63,7 +40,24 @@ jobs:
         run: |
           cd dashboard/HuggingFace
           python new.py
-     
+      - name: Add Generated File
+        run: |
+          git config user.email "${{ secrets.USER_EMAIL }}"
+          git config user.name "${{ secrets.USER_NAME }}"
+          git pull origin main
+          cd dashboard/HuggingFace
+          git add README.md          
+          # Attempt to commit changes and handle errors
+          set +e
+          git commit -m "Add README.md"
+          commit_status=$?
+          set -e
+          if [ $commit_status -eq 0 ]; then
+            git push
+          else
+            echo "No changes to commit or there was an error. Skipping commit and push."
+          fi
+          
       - name: Add Generated File
         run: |
           git config user.email "${{ secrets.USER_EMAIL }}"
@@ -86,3 +80,4 @@ jobs:
           else
             echo "No changes to commit or there was an error. Skipping commit and push."
           fi
+        
